apiVersion : apps/v1
kind : Deployment
metadata:
 name : order-service
 namespace: dev
 labels : 
  app : order-app
spec :
 replicas : 3
 selector:
  matchLabels :
   app : order-app
 template :
  metadata: 
   name : order-service-app
   labels:
    app : order-app
  spec:
   containers :
    - name : order-app
      image : ranjithvoc32022/orders-service:latest
      ports:
       - containerPort: 3000
      resources:
       requests:
        cpu : "100m"
        memory: "128Mi"
       limits:
        cpu : "250m"
        memory: "256Mi"
      readinessProbe:
       tcpSocket:
        port : 3000
       initialDelaySeconds: 5
       periodSeconds: 10
      livenessProbe:
       tcpSocket:
        port : 3000
       initialDelaySeconds: 10
       periodSeconds: 15
      env:
       - name: MYSQL_HOST
         value: "mysql-service"
       - name: MYSQL_PORT
         value: "3306"
       - name: MYSQL_USER
         value: "order_service"
       - name: MYSQL_PASSWORD
         valueFrom:
          secretKeyRef:
           name: mysql-secret
           key: MYSQL_PASSWORD
       - name: MYSQL_DATABASE
         value: "orders_db"
       - name: PYTHON_SERVICE_URL
         value: "http://user-service:8000"
       - name: PORT
         value: "3000"   
